apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  #  namespace: kube-system
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        app: prometheus-node-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule        
      containers:
      - image: prom/node-exporter:v0.16.0
        name: prometheus-node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
      hostNetwork: true
      hostPID: true
      hostIPC: true
      restartPolicy: Always
