apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payment
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: fvovan/payment:v0.0.1
